# create an automation to manage overlay input_booleans by including the following in your automations.yaml:
# !include custom_components/nea_sg_weather/yaml/automations.yaml

- id: 'prevent_stacking_overlays'
  alias: 'Prevent town and region icons from showing concurrently'
  trigger:
  - platform: state
    entity_id: input_boolean.singapore_weather_town_icons, input_boolean.singapore_weather_region_icons
    to: "on"
  action:
  - service: input_boolean.turn_off
    data:
      entity_id: >
        {% if trigger.entity_id == "input_boolean.singapore_weather_town_icons" %}
        input_boolean.singapore_weather_region_icons
        {% elif trigger.entity_id == "input_boolean.singapore_weather_region_icons" %}
        input_boolean.singapore_weather_town_icons
        {% endif %}
